### ISSUE TITLE
Wrap component methods directly?

### ISSUE THREAD

**Issue by gaearon** [loggur/babel-plugin-react-error-catcher#1]
It seems to me that HOC approach isn't the best here. The rendered tree differs significantly from what you'd have in production, and this may introduce tricky edge cases. I feel that it's safer to just replace the `render` method on the existing class itself.

Thoughts?

**Comment by timbur** [comment]
My reasoning for using a HOC here is:

1.  Rather than completely replacing the rendered output upon an error (as it is currently and as it would presumably be upon replacing the `render` method), I would like to immediately revert to the previously working code (only internally of course) while the HOC adds an overlay (or whatever works best) containing the error message and a way to quickly travel to the broken portion of code.  This should be pretty easy to implement the way everything is setup right now.

2.  At some point I would like to wrap arbitrary development controls around components.  Although, that portion may actually work better as a separate module where one might be able to use custom plugins as controls.  I imagine it to be kind of a consolidated, predictable system with an intuitive interface, rather than having half a dozen decorators/HOCs or whatever it might end up being.

As for production differences, I only intended for this to be used in development.  But what do you think about adding some logic that would remove all of the development stuff while keeping the error catching portion and at an absolute minimum?  In that case, just replacing the method(s) like you suggested would probably be ideal.  :)

**Comment by gaearon** [comment]
>I would like to immediately revert to the previously working code 

Why do you think it is beneficial? From my experience it's better to draw attention to the broken code. Because the component isn't unmounted, when you fix it, its props and state will stay the same anyway. So I don't think it's really important (or even desirable) behavior.

>At some point I would like to wrap arbitrary development controls around components. 

I understand this, but this requires a lot of user trust and buy-in. With such custom setup, you are *very* likely to have weird issues (like forgetting to proxy static methods, or proxying them incorrectly). It's fun to experiment with intrusive instrumentation but I don't think *this particular* functionality should require such a large buy-in and breakage potential.

>As for production differences, I only intended for this to be used in development.

I understand. The problem is, even with the workflow I showed at the conference, it's pretty dangerous because you might not notice a red square in development, but the code will crash in production. With “render previous result” and “wrap every component” the differences between production and development versions are *way* too large so any non-trivial app is likely to behave significantly different in prod and dev. This, in my opinion, negates any benefits of such a tool, because people can't trust their code will run correctly once deployed.

**Comment by davidpfahler** [comment]
@timbur I must second @gaearon 's concerns. For this use case, just replacing the render method seems more efficient.

**Comment by timbur** [comment]
Good points!  I'll remove the HOC portion of it and try to just keep this as simple and minimal as possible.  Any extra functionality will be handled within the error reporting component that you'll pass to the catcher.

> just replacing the render method seems more efficient.

I think overloading every method rather than only the `render` method is the best course of action, because there are cases where some code might be executed asynchronously and have no immediate effect on rendering.  I realize that if this is the case, it's not exactly the best component design, but the goal here is to catch all errors originating from React components and allow everything else to function as usual, because let's face it:  very few developers can (or have the time to) build perfectly ideal components with a single pass.  Overloading every method has very minimal overhead and will only make things easier.

> Why do you think it is beneficial? From my experience it's better to draw attention to the broken code. Because the component isn't unmounted, when you fix it, its props and state will stay the same anyway. So I don't think it's really important (or even desirable) behavior.

In the vast majority of cases, you're right.  I agree that drawing attention to the broken code is best.  But when building massively complex systems using modules (not just React components) of which you either don't have full control over or don't know how they work internally, sometimes the cause of an error can be really hard to determine even if you have a full stack trace in front of you.  This might happen due to some odd combination of modules you're using within your component, for example.  And in these cases, imagine the code itself as being just another stateful machine.  You can quickly rule out many causes of the problem by jumping from state to state, immediately testing hypotheses, and eventually narrowing it down to some obscure combination of modules (code) which you know for sure works in one configuration and breaks in another.  It can be pretty tedious to do this without some kind of reversion mechanism.

However, all of that functionality definitely does not belong in this particular plugin and it probably wouldn't even work (at least not without significant effort) within a typical `webpack` workflow.  Thanks for helping me realize that.  :)

Semi-unrelated now, regarding the effects of a development HOC on production builds, if implemented correctly, it would be nearly impossible to produce any unpredictable side effects.  The only way it could have an effect on production behavior is if a developer did something unbelievably stupid.  But you've made another good point, and helped me realize a couple of other ways to do it that won't use a HOC and would make it 100% impossible for it to affect production builds.

So what I'll do now is reduce this plugin to its simplest form and allow you to pass something like `redbox-react` to it.  :)

Other than the error itself, what do you all think should be passed to the handler?  I think to maximize flexibility and allow for custom placement of error messages, the handler should receive the component instance as well.  And perhaps there should also be the option for the handler to return something for the broken component to render.

**Comment by timbur** [comment]
@gaearon @davidpfahler Let me know your thoughts on v1.1.1.  Hopefully the updated README and examples tell you everything you need to know.  :)
